"""empty message

Revision ID: 2f047dfd2601
Revises: b37e182d7115
Create Date: 2017-12-04 21:12:30.030000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f047dfd2601'
down_revision = 'b37e182d7115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('product', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price')
    op.drop_column('product', 'name')
    # ### end Alembic commands ###
