"""empty message

Revision ID: ec39922d8ddf
Revises: 822939e5bb99
Create Date: 2017-12-03 22:46:47.581000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec39922d8ddf'
down_revision = '822939e5bb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('afterComment', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('images', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('length', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('replyCount', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('usefulVoteCount', sa.Integer(), nullable=False))
    op.add_column('reviews', sa.Column('userExpValue', sa.Integer(), nullable=False))
    op.drop_column('reviews', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('username', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('reviews', 'userExpValue')
    op.drop_column('reviews', 'usefulVoteCount')
    op.drop_column('reviews', 'replyCount')
    op.drop_column('reviews', 'length')
    op.drop_column('reviews', 'images')
    op.drop_column('reviews', 'afterComment')
    # ### end Alembic commands ###
